### ISSUE TITLE
Reduce button size on the home page

### ISSUE THREAD

**Issue by moody2times** [moody2times/Whiteboard360#7]
# Button component

There are two button components - one is made with the selector `.btn` and the other `button` tag name. The button tag name selector is applied to all button element. That is not what I want. So, use a class as selector not the tag name.

**Comment by aditya28sarin** [comment]
can you assign this issue to me?

**Comment by moody2times** [comment]
> can you assign this issue to me?

Thank you for your interest but I have resolved it in 0c673bc7f58d22d6f066f36084cf6c156f52125b before I saw your message. Would you be interested in any other issues? Let me know and I can assign those to you.
